name: git-sync

on:
  push:
    branches: [ main ]
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: summer-ospp/git-sync@master
        with:
          source_repo: "https://github.com/summer-ospp/help.git"
          source_branch: "main"
          destination_repo: "git@isrc.iscas.ac.cn:osssc/summer-ospp/help.git"
          destination_branch: "master"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
